#!/usr/bin/env bash
set -euo pipefail # STRICT MODE
IFS=$'\n\t'       # http://redsymbol.net/articles/unofficial-bash-strict-mode/


function downloadFile() {
  URL=$1
  FILE=$(echo ${URL##*/})
  CACHE_DIR="$HOME/.cache/quasar/rpmDownloads"
  mkdir -p $CACHE_DIR
  CACHED_FILE="$CACHE_DIR/$FILE"

  if [[ $URL =~ "/spark/" ]] || [[ $URL =~ "/scala/" ]]
  then
    echo "checking on spark or scala"
    TARGET_DIR="docker/Dockerfiles/Spark/"
    if [ -f $CACHED_FILE ]
    then
      echo "$FILE is cached"
      cp -n $CACHED_FILE $TARGET_DIR
    else
      echo "downloading $FILE"
      curl -o $CACHED_FILE $URL
      cp -n $CACHED_FILE $TARGET_DIR
    fi
  elif [[ $URL =~ "/hadoop/" ]]
  then
    TARGET_DIR="docker/Dockerfiles/Hadoop/"
    if [ -f $CACHED_FILE ]
    then
      cp -n $CACHED_FILE $TARGET_DIR
    else
      curl -o $CACHED_FILE $URL
      cp -n $CACHED_FILE $TARGET_DIR
    fi
  fi
}

function upContainer() {
  docker-compose -f docker/docker-compose.yml up -d $1
}

CONTAINER=$1
if [[ $CONTAINER == "quasar_spark_local_test" ]]
then
  echo "$CONTAINER: not starting a container for spark_local_test..."
elif [[ $CONTAINER == "quasar_mimir" ]]
then
  echo "$CONTAINER: not starting a container for mimir..."
elif [[ $CONTAINER =~ "marklogic" ]]
then
  # download Marklogic RPM and store it in travis cache
  docker/Dockerfiles/Marklogic/getMLRpm
  upContainer $CONTAINER
  sleep 5
elif ([[ $CONTAINER == "quasar_spark_cassandra" ]] || [[ $CONTAINER == "quasar_spark_hdfs" ]] || [[ $CONTAINER == "quasar_spark_ftp" ]] || [[ $CONTAINER == "quasar_spark_elasticsearch" ]])
then
  # download spark, scala, and hadoop tarballs and cache them on travis
  downloadFile "http://www-us.apache.org/dist/spark/spark-2.2.0/spark-2.2.0-bin-hadoop2.7.tgz"
  downloadFile "http://www-us.apache.org/dist/hadoop/common/hadoop-2.7.3/hadoop-2.7.3.tar.gz"
  downloadFile "https://downloads.lightbend.com/scala/2.11.11/scala-2.11.11.tgz"
  upContainer quasar_spark_cluster
  upContainer $CONTAINER
  sleep 5
elif [[ $CONTAINER == "quasar_spark_s3" ]]
then
  upContainer quasar_spark_cluster
  sleep 5
else
  upContainer $CONTAINER
  sleep 5
fi
