quasar_mongodb_2_6:
  container_name: quasar_mongodb_2_6
  image: tutum/mongodb:2.6
  command: mongod --smallfiles
  ports:
    - "27018:27017"

quasar_mongodb_3_0:
  container_name: quasar_mongodb_3_0
  image: mongo:3.0
  command: mongod --smallfiles
  ports:
    - "27019:27017"

quasar_mongodb_read_only:
  container_name: quasar_mongodb_read_only
  image: mongo:3.0
  command: mongod --smallfiles
  ports:
    - "27020:27017"

quasar_mongodb_3_2:
  container_name: quasar_mongodb_3_2
  image: mongo:3.2
  command: ["mongod", "--smallfiles"]
  ports:
    - "27021:27017"

quasar_mongodb_3_4:
  container_name: quasar_mongodb_3_4
  image: mongo:3.4
  command: ["mongod", "--smallfiles"]
  ports:
    - "27022:27017"

quasar_metastore:
  container_name: quasar_metastore
  image: postgres:9.6
  privileged: true
  ports:
    - "5432:5432"

quasar_postgresql:
  container_name: quasar_postgresql
  image: postgres:9.6
  privileged: true
  ports:
    - "5433:5432"

quasar_marklogic_xml:
  container_name: quasar_marklogic_xml
  build: ./Dockerfiles/Marklogic
  dockerfile: MarkLogic-Dockerfile
  ports:
    - "8000-8002:8000-8002"
  mem_limit: 2048m

quasar_marklogic_json:
  container_name: quasar_marklogic_json
  build: ./Dockerfiles/Marklogic
  dockerfile: MarkLogic-Dockerfile
  ports:
    - "9000-9002:8000-8002"
  mem_limit: 2048m

quasar_couchbase:
  container_name: quasar_couchbase
  image: couchbase/server:enterprise-4.5.1
  ports:
    - "8091-8094:8091-8094"
    - "11210:11210"
  mem_limit: 2048m

quasar_spark_cluster:
  container_name: spark
  build: ./Dockerfiles/Spark
  dockerfile: Spark-Dockerfile
  ports:
    - "8081:8080"
    - "7077:7077"
    - "6066:6066"

quasar_elasticsearch:
  container_name: quasar_elasticsearch
  image: docker.elastic.co/elasticsearch/elasticsearch:5.4.2
  ports:
    - 9200:9200
  environment:
    - cluster.name=docker-cluster
    - bootstrap.memory_lock=true
    - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
  ulimits:
    memlock:
      soft: -1
      hard: -1
  mem_limit: 1g
  #volumes:
  #  - esdata1:/usr/share/elasticsearch/data
  #networks:
  #  - esnet

quasar_cassandra:
  container_name: quasar_cassandra
  image: cassandra:latest
  command: /bin/bash -c "sleep 30 && echo ' -- Pausing to let system catch up ... -->' && /docker-entrypoint.sh cassandra -f"
  expose:
    - 7000
    - 7001
    - 7199
    - 9042
    - 9160
  # volumes:
  #   - ./data/cassandra-1:/var/lib/cassandra:rw

quasar_ftp:
  container_name: quasar_ftp
  image: stilliard/pure-ftpd:hardened
  ports:
    - 21:21
    - 30000-30009:30000-30009
  environment:
    - PUBLICHOST=192.168.99.100
  #volumes:
  #  - /tmp:/home/vsftpd

