#!/usr/bin/env bash

set -euo pipefail # STRICT MODE
IFS=$'\n\t'       # http://redsymbol.net/articles/unofficial-bash-strict-mode/

mkdir -p $HOME/marklogic

ML_VERSION="8.0-5.8"
ML_DOWNLOAD_EMAIL="quasarci@slamdata.com"
ML_DOWNLOAD_PASSWORD="quasarci"
ML_DEV_COOKIES=".ml-dev-cookies"
ML_DEV_URL="https://developer.marklogic.com"
ML_DEV_LOGIN="${ML_DEV_URL}/login"
ML_DEV_GET_TOKEN="${ML_DEV_URL}/get-download-url"
ML_DEV_URL="https://developer.marklogic.com"
ML_ASSET_PATH="/download/binaries/8.0/MarkLogic-RHEL6-${ML_VERSION}.x86_64.rpm"
ML_DIR="$HOME/marklogic"
ML_RPM_PATH="$ML_DIR/MarkLogic.rpm"
ML_RPM_SHA1="$ML_DIR/MarkLogic.rpm.sha1"

echo "48cfbd30d003547feb6b60e120abd4542e8b83f9  /tmp/MarkLogic.rpm" > /tmp/MarkLogic.rpm.sha1

curl -X POST --data "email=${ML_DOWNLOAD_EMAIL}&password=${ML_DOWNLOAD_PASSWORD}" -c $ML_DEV_COOKIES $ML_DEV_LOGIN
curl -X POST --data "download=$ML_ASSET_PATH" -b $ML_DEV_COOKIES $ML_DEV_GET_TOKEN > /tmp/json
cat /tmp/json | cut -f 3 -d: | cut -c2- | rev | cut -c3- | rev > /tmp/url
curl -o $ML_RPM_PATH -m 2000 "${ML_DEV_URL}$(cat /tmp/url)"
cd /tmp && shasum --status -c $ML_RPM_SHA1
rm /tmp/MarkLogic.rpm.sha1
