name: build

on:
  pull_request:
    branches: [master]
  push:
    branches: [master]

jobs:
  build:
    name: Build
    strategy:
      matrix:
        os: [ubuntu-latest]
        scala: [2.12.10]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout branch
        uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Setup Git Actor
        run: |
          if ! git config github.actor; then git config --global github.actor slamdata-bot; fi
          git config --global github.token $GITHUB_TOKEN
      - name: Compile and test
        run: |
          ./sbt -DisIsolatedEnv=${ISOLATED_ENV:=false} ++${{ matrix.scala }} checkHeaders test:compile "testOnly -- failtrace"
      - name: Upload target
        uses: actions/upload-artifact@v1
        with:
          name: target
          path: target
      - name: Echo GitHub Worlflow
        run: echo $GITHUB_WORKFLOW

  commonResources:
    name: Run common scripts
    needs: [build]
    runs-on: [ubuntu-latest]
    steps:
      - name: Checkout branch
        uses: actions/checkout@v2
      - name: Download target artifacts
        uses: actions/download-artifact@v1
        with:
          name: target
      - name: Install common resources
        run: ./sbt transferCommonResources
      - name: Install ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: '2.6' 
      - name: Common setup
        run: ./scripts/commonSetup
      - name: Publish and Tag
        run: ./scripts/quasarPublishAndTag
      - name: Check auto merge
        env:
          VERSIONS: $(git diff HEAD^ | grep -e '^[-+][0-9]' | sed 's/^[+\-]//' | sed 's/\.[0-9]*$//' | uniq | wc -l)
          CLONE_DIR: $(mktemp -d "/tmp/slamdata-bump.XXXXXXXX")
          IS_REVISION_LABEL: contains( github.event.pull_request.labels.*.name, 'revision')
          REPO_SLUG: ${{ github.repository }}
          PR_NUMBER: $(echo "$GITHUB_REF" | cut -d'/' -f3)
        run: ./scripts/checkAndAutoMerge

      #- name: Discord Post 
      #  run: ./scripts/discordTravisPost success https://discordapp.com/api/webhooks/$DISCORD_WEBHOOK_TOKENS
