name: build

on:
  pull_request:
    branches: [master]
  push:
    branches: [master]

jobs:
  build:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        sbt: [2.12.10]
    steps:
      - name: Checkout branch
        uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Compile and test
        run: |
          ./sbt -DisIsolatedEnv=${ISOLATED_ENV:=false} ++${{ matrix.sbt }} checkHeaders test:compile "testOnly -- failtrace"
      - name: Upload target
        uses: actions/upload-artifact@v1
        with:
          name: target
          path: target
